id: IAA09994C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:14:30+00:00'
last_modified: '2022-06-08T08:51:55.901213+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22298
  title: རྟ་རྒྱུགས་དཔྱིད་ཀྱི་ཉི་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    47CD:
      image_group_id: I1KG18065
      title: ''
      total_pages: 302
      order: 1
      base_file: 47CD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
