id: P009134
initial_creation_type: ocr
source_metadata:
  id: bdr:W22298
  title: རྟ་རྒྱུགས་དཔྱིད་ཀྱི་ཉི་མ།
  author: ''
  volumes:
    1a8d4fda36b747f38820104b8b10cd94:
      image_group_id: I1KG18065
      title: ''
      volume_number: 1
      total_pages: 302
      base_file: v001.txt
